achat textile de seconde main
datagir/nosgestesclimat pull request #1004
Opened 2021-04-20 14:03 UTC by Benjamin-Boisserie-ABC

Pour comprendre d’où vient le 0.104 (0.125/1.2), se référer au fichier Excel attaché (onglet textile) 

Ce chiffre est bien évidemment à discuter ! 

[Impact_GES_2ndmain.xlsx](https://github.com/datagir/nosgestesclimat/files/6344121/Impact_GES_2ndmain.xlsx)

2021-11-02 16:46 UTC, laem commented
@Benjamin-Boisserie-ABC nous avons changé le mode de calcul du textile, qui  n'est plus un facteur d'émission, donc le mode de calcul n'est plus possible. 

Par contre, je me demande si on ne peut pas appliquer un facteur au montant calculé de l'empreinte textile renseignée par l'utilisateur via la mosaïque textile ?

2021-11-02 16:47 UTC, laem requested changes
@Benjamin-Boisserie-ABC nous avons changé le mode de calcul du textile, qui  n'est plus un facteur d'émission, donc le mode de calcul n'est plus possible. 

Par contre, je me demande si on ne peut pas appliquer un facteur au montant calculé de l'empreinte textile renseignée par l'utilisateur via la mosaïque textile ?

2021-12-02 15:40 UTC, Benjamin-Boisserie-ABC commented
@laem via les données ADEME il est possible de calculer l'impact d'un produit textile de 2nd main (ou électroménager/électronique d'ailleurs). Je l'ai fait. C'est le même fichier que celui donné dans mon premier commentaire (onglet "Textiles" colonne K). 

Je me permets donc de rouvrir la PR. Je ferais une proposition d'intégration très vite
[Impact_GES_2ndmain.xlsx](https://github.com/datagir/nosgestesclimat/files/7643192/Impact_GES_2ndmain.xlsx)

2021-12-14 14:00 UTC, Benjamin-Boisserie-ABC commented
Trouver un moyen d'aborder les notions 
- de préservations des biens (à l'instar de ce qu'on fait sur les électroménagers )
- revente des biens dans le marché de l'occasion
- utilisation du marché de l'occasion (note utilisateurs pour passer le message "si Iphone 13 sur backmarket c'est du neuf", éventuellement une pop up qui dirait "acheter d'occasion n'est pas toujours de 2nd main")

Éventuellement "parler de réemploi" qui introduit une notion réelle d'un emploi premier ayant eu déjà lieu

2022-04-13 13:09 UTC, Benjamin-Boisserie-ABC commented
PR fermée et qui sera réouvert une fois le cadrage méthodologique revu.
A regarder "Étude d'évaluation des gisements d'évitement, des potentiels de réduction de déchets et des impact environnementaux évités" chapitre 6.11

2022-04-13 13:09 UTC, closed without merging